package BourseCorba;


/**
* BourseCorba/_AlarmeImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

public abstract class _AlarmeImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements BourseCorba.Alarme, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AlarmeImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_type", new java.lang.Integer (0));
    _methods.put ("_set_type", new java.lang.Integer (1));
    _methods.put ("_get_seuil", new java.lang.Integer (2));
    _methods.put ("_set_seuil", new java.lang.Integer (3));
    _methods.put ("notifie", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BourseCorba/Alarme/_get_type
       {
         short $result = (short)0;
         $result = this.type ();
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 1:  // BourseCorba/Alarme/_set_type
       {
         short newType = in.read_short ();
         this.type (newType);
         out = $rh.createReply();
         break;
       }

       case 2:  // BourseCorba/Alarme/_get_seuil
       {
         double $result = (double)0;
         $result = this.seuil ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // BourseCorba/Alarme/_set_seuil
       {
         double newSeuil = in.read_double ();
         this.seuil (newSeuil);
         out = $rh.createReply();
         break;
       }

       case 4:  // BourseCorba/Alarme/notifie
       {
         this.notifie ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BourseCorba/Alarme:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AlarmeImplBase
