package BourseCorba;


/**
* BourseCorba/HistoriqueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

abstract public class HistoriqueHelper
{
  private static String  _id = "IDL:BourseCorba/Historique:1.0";

  public static void insert (org.omg.CORBA.Any a, BourseCorba.Historique that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BourseCorba.Historique extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BourseCorba.HistoriqueHelper.id (), "Historique");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BourseCorba.Historique read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HistoriqueStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BourseCorba.Historique value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BourseCorba.Historique narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BourseCorba.Historique)
      return (BourseCorba.Historique)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BourseCorba._HistoriqueStub stub = new BourseCorba._HistoriqueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BourseCorba.Historique unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BourseCorba.Historique)
      return (BourseCorba.Historique)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BourseCorba._HistoriqueStub stub = new BourseCorba._HistoriqueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
