package BourseCorba;


/**
* BourseCorba/ServerException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

public final class ServerException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ServerException ()
  {
    super(ServerExceptionHelper.id());
  } // ctor

  public ServerException (String _reason)
  {
    super(ServerExceptionHelper.id());
    reason = _reason;
  } // ctor


  public ServerException (String $reason, String _reason)
  {
    super(ServerExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ServerException
