package BourseCorba;


/**
* BourseCorba/ServiceWebOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

public interface ServiceWebOperations 
{
  int creerTitre (String libelle, double coursIntro);
  void majCoursAction (int idTitre, double nouveauCours);
} // interface ServiceWebOperations
