package BourseCorba;


/**
* BourseCorba/_AdminStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

public class _AdminStub extends org.omg.CORBA.portable.ObjectImpl implements BourseCorba.Admin
{


  // retourne l identifiant de l utilisateur
  public int insererUtilisateur (String nom, String prenom, String login, String mdp, int role) throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insererUtilisateur", true);
                $out.write_string (nom);
                $out.write_string (prenom);
                $out.write_string (login);
                $out.write_string (mdp);
                $out.write_long (role);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insererUtilisateur (nom, prenom, login, mdp, role        );
            } finally {
                _releaseReply ($in);
            }
  } // insererUtilisateur


  // retourne l identifiant du compte
  public int creerCompte (double cash)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerCompte", true);
                $out.write_double (cash);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerCompte (cash        );
            } finally {
                _releaseReply ($in);
            }
  } // creerCompte

  public void affecterCompte (int idUser, int idCompte) throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("affecterCompte", true);
                $out.write_long (idUser);
                $out.write_long (idCompte);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                affecterCompte (idUser, idCompte        );
            } finally {
                _releaseReply ($in);
            }
  } // affecterCompte

  public BourseCorba.CompteAdmin[] getComptes ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getComptes", true);
                $in = _invoke ($out);
                BourseCorba.CompteAdmin $result[] = BourseCorba.ListeCompteAdminHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getComptes (        );
            } finally {
                _releaseReply ($in);
            }
  } // getComptes

  public void ajoutCash (int idCompte, double valeur) throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajoutCash", true);
                $out.write_long (idCompte);
                $out.write_double (valeur);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ajoutCash (idCompte, valeur        );
            } finally {
                _releaseReply ($in);
            }
  } // ajoutCash

  public void diminuerCash (int idCompte, double valeur) throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("diminuerCash", true);
                $out.write_long (idCompte);
                $out.write_double (valeur);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                diminuerCash (idCompte, valeur        );
            } finally {
                _releaseReply ($in);
            }
  } // diminuerCash

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BourseCorba/Admin:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _AdminStub
