package BourseCorba;


/**
* BourseCorba/_BourseStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

public class _BourseStub extends org.omg.CORBA.portable.ObjectImpl implements BourseCorba.Bourse
{

  public BourseCorba.ServiceWeb getServiceWeb () throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getServiceWeb", true);
                $in = _invoke ($out);
                BourseCorba.ServiceWeb $result = BourseCorba.ServiceWebHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getServiceWeb (        );
            } finally {
                _releaseReply ($in);
            }
  } // getServiceWeb

  public BourseCorba.Compte connectUser (String login, String mdp) throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("connectUser", true);
                $out.write_string (login);
                $out.write_string (mdp);
                $in = _invoke ($out);
                BourseCorba.Compte $result = BourseCorba.CompteHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connectUser (login, mdp        );
            } finally {
                _releaseReply ($in);
            }
  } // connectUser

  public BourseCorba.Admin connectAdmin (String login, String mdp) throws BourseCorba.ServerException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("connectAdmin", true);
                $out.write_string (login);
                $out.write_string (mdp);
                $in = _invoke ($out);
                BourseCorba.Admin $result = BourseCorba.AdminHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BourseCorba/ServerException:1.0"))
                    throw BourseCorba.ServerExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connectAdmin (login, mdp        );
            } finally {
                _releaseReply ($in);
            }
  } // connectAdmin

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BourseCorba/Bourse:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _BourseStub
