package BourseCorba;


/**
* BourseCorba/_HistoriqueImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

public abstract class _HistoriqueImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements BourseCorba.Historique, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _HistoriqueImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_valeur", new java.lang.Integer (0));
    _methods.put ("_set_valeur", new java.lang.Integer (1));
    _methods.put ("_get_dateHistorique", new java.lang.Integer (2));
    _methods.put ("_set_dateHistorique", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BourseCorba/Historique/_get_valeur
       {
         double $result = (double)0;
         $result = this.valeur ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // BourseCorba/Historique/_set_valeur
       {
         double newValeur = in.read_double ();
         this.valeur (newValeur);
         out = $rh.createReply();
         break;
       }

       case 2:  // BourseCorba/Historique/_get_dateHistorique
       {
         String $result = null;
         $result = this.dateHistorique ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // BourseCorba/Historique/_set_dateHistorique
       {
         String newDateHistorique = in.read_string ();
         this.dateHistorique (newDateHistorique);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BourseCorba/Historique:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _HistoriqueImplBase
