package BourseCorba;


/**
* BourseCorba/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public interface AdminOperations 
{

  // retourne l identifiant de l utilisateur
  int insererUtilisateur (String nom, String prenom, String login, String mdp, int role) throws BourseCorba.ServerException;

  // retourne l identifiant du compte
  int creerCompte (double cash);
  void affecterCompte (int idUser, int idCompte) throws BourseCorba.ServerException;
  BourseCorba.CompteAdmin[] getComptes ();
  void ajoutCash (int idCompte, double valeur) throws BourseCorba.ServerException;
  void diminuerCash (int idCompte, double valeur) throws BourseCorba.ServerException;
} // interface AdminOperations
