package BourseCorba;

/**
* BourseCorba/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public BourseCorba.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (BourseCorba.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BourseCorba.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BourseCorba.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BourseCorba.AdminHelper.type ();
  }

}
