package BourseCorba;


/**
* BourseCorba/BourseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

public interface BourseOperations 
{
  BourseCorba.ServiceWeb getServiceWeb () throws BourseCorba.ServerException;
  BourseCorba.Compte connectUser (String login, String mdp) throws BourseCorba.ServerException;
  BourseCorba.Admin connectAdmin (String login, String mdp) throws BourseCorba.ServerException;
} // interface BourseOperations
