package BourseCorba;


/**
* BourseCorba/BourseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public interface BourseOperations 
{
  BourseCorba.ServiceWeb getServiceWeb () throws BourseCorba.ServerException;
  BourseCorba.Compte connectUser (String login, String mdp) throws BourseCorba.ServerException;
  BourseCorba.Admin connectAdmin (String login, String mdp) throws BourseCorba.ServerException;
} // interface BourseOperations
