package BourseCorba;

/**
* BourseCorba/BourseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 13 mai 2008 19 h 17 CEST
*/

public final class BourseHolder implements org.omg.CORBA.portable.Streamable
{
  public BourseCorba.Bourse value = null;

  public BourseHolder ()
  {
  }

  public BourseHolder (BourseCorba.Bourse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BourseCorba.BourseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BourseCorba.BourseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BourseCorba.BourseHelper.type ();
  }

}
