package BourseCorba;


/**
* BourseCorba/ClientAlarmeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 13 mai 2008 19 h 17 CEST
*/

public interface ClientAlarmeOperations 
{
  void notifie (int idTitre, double nouveauCours);
} // interface ClientAlarmeOperations
