package BourseCorba;


/**
* BourseCorba/ClientAlarmeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public interface ClientAlarmeOperations 
{
  void notifie (int idTitre, double nouveauCours);
} // interface ClientAlarmeOperations
