package BourseCorba;


/**
* BourseCorba/CompteAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 13 mai 2008 19 h 17 CEST
*/

public final class CompteAdmin implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public String id = null;

  public CompteAdmin ()
  {
  } // ctor

  public CompteAdmin (String _nom, String _id)
  {
    nom = _nom;
    id = _id;
  } // ctor

} // class CompteAdmin
