package BourseCorba;


/**
* BourseCorba/CompteAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public final class CompteAdmin implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public String id = null;
  public double cash = (double)0;

  public CompteAdmin ()
  {
  } // ctor

  public CompteAdmin (String _nom, String _id, double _cash)
  {
    nom = _nom;
    id = _id;
    cash = _cash;
  } // ctor

} // class CompteAdmin
