package BourseCorba;

/**
* BourseCorba/CompteAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

public final class CompteAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public BourseCorba.CompteAdmin value = null;

  public CompteAdminHolder ()
  {
  }

  public CompteAdminHolder (BourseCorba.CompteAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BourseCorba.CompteAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BourseCorba.CompteAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BourseCorba.CompteAdminHelper.type ();
  }

}
