package BourseCorba;


/**
* BourseCorba/HistoriqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

public interface HistoriqueOperations 
{
  double valeur ();
  void valeur (double newValeur);
  String dateHistorique ();
  void dateHistorique (String newDateHistorique);
} // interface HistoriqueOperations
