package BourseCorba;


/**
* BourseCorba/HistoriqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public interface HistoriqueOperations 
{
  double valeur ();
  void valeur (double newValeur);
  String dateHistorique ();
  void dateHistorique (String newDateHistorique);
} // interface HistoriqueOperations
