package BourseCorba;


/**
* BourseCorba/ListeCompteAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

public final class ListeCompteAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public BourseCorba.CompteAdmin value[] = null;

  public ListeCompteAdminHolder ()
  {
  }

  public ListeCompteAdminHolder (BourseCorba.CompteAdmin[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BourseCorba.ListeCompteAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BourseCorba.ListeCompteAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BourseCorba.ListeCompteAdminHelper.type ();
  }

}
