package BourseCorba;


/**
* BourseCorba/ServiceWeb.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public interface ServiceWeb extends ServiceWebOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceWeb
