package BourseCorba;


/**
* BourseCorba/ServiceWeb.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

public interface ServiceWeb extends ServiceWebOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceWeb
