package BourseCorba;


/**
* BourseCorba/ServiceWebHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

abstract public class ServiceWebHelper
{
  private static String  _id = "IDL:BourseCorba/ServiceWeb:1.0";

  public static void insert (org.omg.CORBA.Any a, BourseCorba.ServiceWeb that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BourseCorba.ServiceWeb extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BourseCorba.ServiceWebHelper.id (), "ServiceWeb");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BourseCorba.ServiceWeb read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServiceWebStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BourseCorba.ServiceWeb value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BourseCorba.ServiceWeb narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BourseCorba.ServiceWeb)
      return (BourseCorba.ServiceWeb)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BourseCorba._ServiceWebStub stub = new BourseCorba._ServiceWebStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BourseCorba.ServiceWeb unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BourseCorba.ServiceWeb)
      return (BourseCorba.ServiceWeb)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BourseCorba._ServiceWebStub stub = new BourseCorba._ServiceWebStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
