package BourseCorba;


/**
* BourseCorba/ServiceWebOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public interface ServiceWebOperations 
{
  int creerTitre (String libelle, double coursIntro);
  void majCoursAction (int idTitre, double nouveauCours);
} // interface ServiceWebOperations
