package BourseCorba;


/**
* BourseCorba/TitreDetailleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 8 avril 2008 19 h 04 CEST
*/

abstract public class TitreDetailleHelper
{
  private static String  _id = "IDL:BourseCorba/TitreDetaille/TitreDetaille:1.0";

  public static void insert (org.omg.CORBA.Any a, BourseCorba.TitreDetaille that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BourseCorba.TitreDetaille extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "libelle",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "dateIntroduction",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[3] = new org.omg.CORBA.StructMember (
            "coursIntrodution",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[4] = new org.omg.CORBA.StructMember (
            "coursLePlusHaut",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[5] = new org.omg.CORBA.StructMember (
            "coursLePlusBas",
            _tcOf_members0,
            null);
          _tcOf_members0 = BourseCorba.HistoriqueHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BourseCorba.ListeHistoriquesHelper.id (), "ListeHistoriques", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "histo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (BourseCorba.TitreDetailleHelper.id (), "TitreDetaille", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BourseCorba.TitreDetaille read (org.omg.CORBA.portable.InputStream istream)
  {
    BourseCorba.TitreDetaille value = new BourseCorba.TitreDetaille ();
    value.libelle = istream.read_string ();
    value.id = istream.read_long ();
    value.dateIntroduction = istream.read_string ();
    value.coursIntrodution = istream.read_double ();
    value.coursLePlusHaut = istream.read_double ();
    value.coursLePlusBas = istream.read_double ();
    value.histo = BourseCorba.ListeHistoriquesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BourseCorba.TitreDetaille value)
  {
    ostream.write_string (value.libelle);
    ostream.write_long (value.id);
    ostream.write_string (value.dateIntroduction);
    ostream.write_double (value.coursIntrodution);
    ostream.write_double (value.coursLePlusHaut);
    ostream.write_double (value.coursLePlusBas);
    BourseCorba.ListeHistoriquesHelper.write (ostream, value.histo);
  }

}
