package BourseCorba;

/**
* BourseCorba/TitreDetailleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public final class TitreDetailleHolder implements org.omg.CORBA.portable.Streamable
{
  public BourseCorba.TitreDetaille value = null;

  public TitreDetailleHolder ()
  {
  }

  public TitreDetailleHolder (BourseCorba.TitreDetaille initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BourseCorba.TitreDetailleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BourseCorba.TitreDetailleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BourseCorba.TitreDetailleHelper.type ();
  }

}
