package BourseCorba;


/**
* BourseCorba/TitreDetaille.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* dimanche 1 juin 2008 16 h 45 CEST
*/

public final class TitreDetaille implements org.omg.CORBA.portable.IDLEntity
{
  public String libelle = null;
  public int id = (int)0;
  public String dateIntroduction = null;
  public double coursIntrodution = (double)0;
  public double coursLePlusHaut = (double)0;
  public double coursLePlusBas = (double)0;
  public BourseCorba.Historique histo[] = null;

  public TitreDetaille ()
  {
  } // ctor

  public TitreDetaille (String _libelle, int _id, String _dateIntroduction, double _coursIntrodution, double _coursLePlusHaut, double _coursLePlusBas, BourseCorba.Historique[] _histo)
  {
    libelle = _libelle;
    id = _id;
    dateIntroduction = _dateIntroduction;
    coursIntrodution = _coursIntrodution;
    coursLePlusHaut = _coursLePlusHaut;
    coursLePlusBas = _coursLePlusBas;
    histo = _histo;
  } // ctor

} // class TitreDetaille
