package BourseCorba;


/**
* BourseCorba/Titre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bourse.idl
* mardi 20 mai 2008 18 h 27 CEST
*/

public final class Titre implements org.omg.CORBA.portable.IDLEntity
{
  public String libelle = null;
  public int id = (int)0;
  public double cours = (double)0;

  public Titre ()
  {
  } // ctor

  public Titre (String _libelle, int _id, double _cours)
  {
    libelle = _libelle;
    id = _id;
    cours = _cours;
  } // ctor

} // class Titre
